version: '3.4'

services:
  grot-mysql:
    container_name: grot-mysql
    restart: always
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./test-sql-2:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grot
      MYSQL_USER: grot
      MYSQL_PASSWORD: grot
  grotmigrations:
    container_name: grotmigrations
    image: ${DOCKER_REGISTRY-}grotmigrations
    links:
      - grot-mysql
    build:
      context: .
      dockerfile: GrotMigrations/Dockerfile
    depends_on: 
      - grot-mysql    
  grotwebapi:
    container_name: grotapi
    image: ${DOCKER_REGISTRY-}grotwebapi
    links:
      - grot-mysql
    build:
      context: .
      dockerfile: GrotWebApi/Dockerfile
    ports:
      - "80"
  grot-front:
    container_name: grot-front
    image: ${DOCKER_REGISTRY-}grot-front
    links:
      - grotwebapi
    environment:
      - ENV_BACKEND_URI='http://grotapi/api'
      - ENV_IS_PRODUCTION=false
    build:
      context: .
      dockerfile: grot-front/Dockerfile
    depends_on: 
      - grotwebapi
    ports:
      - "80:80"
      - "443:443"
  